# Generated by Django 6.1.1 on 2026-09-14 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('kaz_history', 'История Казахстана'), ('reading', 'Грамотность чтения'), ('math_literacy', 'Математическая грамотность'), ('profile', 'Профильный предмет')], max_length=20)),
                ('name_kk', models.CharField(max_length=100, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (англ)')),
                ('category', models.CharField(choices=[('mandatory', 'Обязательный'), ('profile', 'Профильный')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('teacher_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('zavuch_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('student_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(11)])),
                ('letter', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е')], max_length=2)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school')),
            ],
            options={
                'ordering': ['grade', 'letter'],
                'unique_together': {('school', 'grade', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('kaz_history', 'История Казахстана'), ('reading', 'Грамотность чтения'), ('math_literacy', 'Математическая грамотность'), ('profile', 'Профильный предмет')], max_length=20)),
                ('question_type', models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных')], default='single', max_length=10)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершён'), ('annulled', 'Аннулирован')], default='in_progress', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('score_kaz_history', models.IntegerField(default=0)),
                ('score_reading', models.IntegerField(default=0)),
                ('score_math_literacy', models.IntegerField(default=0)),
                ('score_profile_1', models.IntegerField(default=0)),
                ('score_profile_2', models.IntegerField(default=0)),
                ('passed_thresholds', models.BooleanField(default=False)),
                ('profile_subject_1', models.CharField(blank=True, max_length=100)),
                ('profile_subject_2', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('director', 'Директор'), ('zavuch', 'Завуч')], max_length=20)),
                ('is_subject_teacher', models.BooleanField(default=False)),
                ('is_homeroom_teacher', models.BooleanField(default=False)),
                ('homeroom_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher', to='core.schoolclass')),
                ('profile_subject_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_profile_1', to='core.subject')),
                ('profile_subject_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_profile_2', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_snapshot', models.TextField(blank=True)),
                ('correct_answer_snapshot', models.CharField(blank=True, max_length=4)),
                ('question_type_snapshot', models.CharField(blank=True, max_length=10)),
                ('subject_snapshot', models.CharField(blank=True, max_length=20)),
                ('chosen', models.CharField(blank=True, max_length=4)),
                ('score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
