# Generated by Django 6.1.1 on 2026-09-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вариант E'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_f',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вариант F'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (для учителя)')),
                ('context_text', models.TextField(verbose_name='Текст (контекст)')),
                ('block', models.CharField(choices=[('reading', 'Грамотность чтения'), ('kaz_history', 'История Казахстана'), ('math_literacy', 'Математическая грамотность'), ('profile', 'Профильный предмет')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_groups', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_groups', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='core.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_groups', to='core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.questiongroup'),
        ),
    ]
