# Generated by Django 6.1.1 on 2026-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_option_e_question_option_f_questiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='group_context_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='group_title_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
