# Generated by Django 6.1.1 on 2026-09-15 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_answer_group_context_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='chosen',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_answer_snapshot',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='answer',
            name='subject_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=6),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homeroom_teacher', True)), fields=('homeroom_class',), name='unique_homeroom_teacher_per_class'),
        ),
    ]
