# Generated by Django 6.1.1 on 2026-09-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answer_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='core.examsession'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_f',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='context_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
