# Generated by Django 6.1.1 on 2026-09-24 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testattempt_session_alter_question_option_e_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='difficulty_snapshot',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='answer',
            name='kind_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='answer',
            name='matching_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='matching_data_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('A', 'Оңай'), ('B', 'Орташа'), ('C', 'Қиын')], db_index=True, default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/%Y/%m/', verbose_name='Сурет'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted_by_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('context', 'Контекстный')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='difficulty',
            field=models.CharField(choices=[('A', 'Оңай'), ('B', 'Орташа'), ('C', 'Қиын')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных'), ('matching', 'Сопоставление')], default='single', max_length=10),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['block', 'difficulty', 'status'], name='core_questi_block_61fc61_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty', 'status'], name='core_questi_subject_99dc3d_idx'),
        ),
    ]
