# Generated by Django 6.1.1 on 2026-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_difficulty_snapshot_answer_image_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='group_image_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/images/%Y/%m/', verbose_name='Контекст суреті'),
        ),
    ]
