# Generated by Django 6.1.1 on 2026-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_answer_group_image_snapshot_questiongroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_plain',
            field=models.TextField(blank=True, help_text='Қарапайым мәтін (пробел, тыныс белгілері)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='MathLive формуласы (LaTeX)'),
        ),
    ]
