# Generated by Django 6.1.1 on 2026-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_text_plain_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_plain',
            field=models.TextField(blank=True, help_text='Қарапайым мәтін (пробелмен)'),
        ),
    ]
