# Generated by Django 6.1.1 on 2026-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_question_text_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
